services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=iman123
      - DATABASE_NAME=chat_app
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_c
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iman123
      POSTGRES_DB: chat_app
    ports:
      - '5432:5432'

