services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    depends_on:
      - backend  # Ensure the frontend waits for the backend to start
    environment:
      - BACKEND_URL=http://backend:4000  # Backend URL for socket connection

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=iman123
      - DATABASE_NAME=chat_app
      - SOCKET_PORT=4000  # Specify the port for the socket server
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_c
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iman123
      POSTGRES_DB: chat_app
    ports:
      - '5432:5432'

networks:
  default:
    driver: bridge
